#!/bin/bash
set -e

# ============================================================
# Mediend CRM - Single-container deploy (port 3000)
#
# Run this directly on the VPS. It will:
#   1. Pull latest code from GitHub
#   2. Build the app image with the new code
#   3. Recreate the app container on 127.0.0.1:3000
#   4. Wait for /api/health to return 200
#   5. Prune dangling images
#
# Nginx setup (one-time):
#   /etc/nginx/conf.d/mediend-upstream.conf:
#     upstream mediend_app { server 127.0.0.1:3000; }
#   In your main server block: proxy_pass http://mediend_app;
#   Add: client_max_body_size 25m;
#
# Usage: ./deploy.sh
# ============================================================

APP_DIR="/root/mediend.workspace"
NGINX_CONF="/etc/nginx/conf.d/mediend-upstream.conf"
PORT=3000

cd "$APP_DIR"

echo "--- Pulling latest code..."
git pull origin main

COMMIT=$(git rev-parse --short HEAD)
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "===> Deploying commit $COMMIT..."

# ── Build & (re)start the app, worker, and redis ───────────
# Build sequentially — parallel Next.js builds can OOM a 4GB VPS.
DEPLOY_COMMIT="$COMMIT" DEPLOY_TIME="$TIMESTAMP" docker compose build app
DEPLOY_COMMIT="$COMMIT" DEPLOY_TIME="$TIMESTAMP" docker compose build worker-bulk-reassign
DEPLOY_COMMIT="$COMMIT" DEPLOY_TIME="$TIMESTAMP" docker compose up -d --remove-orphans redis app worker-bulk-reassign

# ── Wait for health check ───────────────────────────────────
echo "--- Waiting for app to become healthy (max 120s)..."
elapsed=0
while true; do
  http_code=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:${PORT}/api/health" 2>/dev/null || echo "000")
  if [ "$http_code" = "200" ]; then
    echo "--- app is healthy!"
    break
  fi
  if [ "$elapsed" -ge 120 ]; then
    echo "!!! app failed health check after 120s."
    docker compose logs --tail=50 app || true
    exit 1
  fi
  sleep 3
  elapsed=$((elapsed + 3))
  echo "    waiting... (${elapsed}/120s, http=$http_code)"
done

# ── Ensure nginx upstream points at port 3000 ────────────────
# (Idempotent; also corrects any leftover blue/green 3100 config.)
DESIRED="upstream mediend_app { server 127.0.0.1:${PORT}; }"
if [ ! -f "$NGINX_CONF" ] || ! grep -q "127.0.0.1:${PORT};" "$NGINX_CONF"; then
  echo "--- Writing nginx upstream -> 127.0.0.1:${PORT}..."
  cat > "$NGINX_CONF" <<EOF
# Auto-generated by deploy.sh
$DESIRED
EOF
  nginx -t && systemctl reload nginx
  echo "--- Nginx reloaded."
fi

# ── Cleanup ──────────────────────────────────────────────────
docker image prune -f
echo "--- Final status:"
docker compose ps

echo ""
echo "===> Deployed $COMMIT at $TIMESTAMP"
echo "===> App: https://workspace.mediend.com"
echo "===> Status: https://status.mediend.com"
