-- AlterTable
ALTER TABLE "PLRecord" ADD COLUMN "actualImplantCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PLRecord" ADD COLUMN "actualInstrumentCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PLRecord" ADD COLUMN "hospitalRecoverAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
