'use client'

import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line as RechartsLine, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, BarChart3, CalendarDays, CircleDollarSign, Clock3, Funnel, LineChart as LineChartIcon, Megaphone, Target, Users } from 'lucide-react'
import { AuthenticatedLayout } from '@/components/authenticated-layout'
import { apiGet } from '@/lib/api-client'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'

type Group = { label: string; leads: number; opd: number; ipd: number; revenue: number; profit: number; conversionRate: number }
type Data = {
  summary: Record<string, number | null>
  funnel: Array<{ label: string; value: number }>
  sla: { within5: number; within15: number; late: number; pending: number; called: number; within15Rate: number }
  targets: { assigned: number; achieved: number; remaining: number; achievement: number; daysElapsed: number; daysRemaining: number; requiredRunRate: number; currentRunRate: number; projected: number | null }
  groups: { city: Group[]; source: Group[]; bd: Group[]; team: Group[]; category: Group[]; hospital: Group[]; campaign: Group[]; monthly: Group[] }
  finance: { plRecords: number; revenue: number; netProfit: number; share: number; outstanding: number; outstandingCases: number }
  dataAvailability: Record<string, boolean>
  filters: { cities: string[]; sources: string[]; categories: string[]; bds: Array<{ id: string; name: string }> }
}

const tabs = [
  ['salesOverview', 'Sales overview', BarChart3], ['salesTeams', 'TL performance', Users], ['salesInsights', 'Sales insights', LineChartIcon],
  ['marketingOverview', 'Marketing overview', Megaphone], ['marketingPerformance', 'Marketing performance', Activity], ['marketingAlerts', 'Marketing alerts', Clock3],
  ['financialOverview', 'Financial overview', CircleDollarSign], ['outstanding', 'Outstanding', CalendarDays], ['cashFlow', 'Cash flow', Activity], ['hospitalPnl', 'Hospital P&L', BarChart3], ['profitability', 'Profitability', Target],
] as const
const colors = ['#22c55e', '#38bdf8', '#a78bfa', '#f59e0b', '#f43f5e', '#14b8a6']
const today = new Date().toISOString().slice(0, 10)
const firstOfMonth = `${today.slice(0, 8)}01`

function money(value: number | null | undefined) { return `₹${Math.round(value ?? 0).toLocaleString('en-IN')}` }
function percent(value: number | null | undefined) { return value === null || value === undefined ? '—' : `${value.toFixed(1)}%` }
function MetricCard({ label, value, note, tone = 'emerald' }: { label: string; value: string | number; note?: string; tone?: 'emerald' | 'sky' | 'violet' | 'amber' | 'rose' }) {
  const style = { emerald: 'from-emerald-500/20 border-emerald-500/35', sky: 'from-sky-500/20 border-sky-500/35', violet: 'from-violet-500/20 border-violet-500/35', amber: 'from-amber-500/20 border-amber-500/35', rose: 'from-rose-500/20 border-rose-500/35' }[tone]
  return <Card className={cn('border bg-gradient-to-br to-card', style)}><CardContent className="p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight">{value}</p>{note && <p className="mt-1 text-xs text-muted-foreground">{note}</p>}</CardContent></Card>
}
function ChartCard({ title, children }: { title: string; children: React.ReactNode }) { return <Card><CardHeader className="pb-1"><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="h-[290px] pt-2">{children}</CardContent></Card> }
function GroupTable({ title, rows }: { title: string; rows: Group[] }) { return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="max-h-[360px] overflow-auto p-0"><table className="w-full text-sm"><thead className="sticky top-0 bg-card text-left text-xs text-muted-foreground"><tr><th className="px-5 py-3">Name</th><th>Leads</th><th>OPD</th><th>IPD</th><th>Conversion</th><th className="pr-5 text-right">Profit</th></tr></thead><tbody>{rows.slice(0, 12).map((row) => <tr className="border-t" key={row.label}><td className="px-5 py-3 font-medium">{row.label}</td><td>{row.leads}</td><td>{row.opd}</td><td>{row.ipd}</td><td>{percent(row.conversionRate)}</td><td className="pr-5 text-right">{money(row.profit)}</td></tr>)}{!rows.length && <tr><td className="px-5 py-6 text-muted-foreground" colSpan={6}>No matching data</td></tr>}</tbody></table></CardContent></Card> }

export default function KpiDashboardPage() {
  const [active, setActive] = useState<(typeof tabs)[number][0]>('salesOverview')
  const [draft, setDraft] = useState({ startDate: firstOfMonth, endDate: today, city: '', source: '', category: '', bdId: '' })
  const [filters, setFilters] = useState(draft)
  const query = useMemo(() => new URLSearchParams(Object.entries(filters).filter(([, value]) => value)).toString(), [filters])
  const { data, isLoading, isFetching } = useQuery<Data>({ queryKey: ['kpi-dashboard', query], queryFn: () => apiGet(`/api/analytics/kpi-dashboard?${query}`) })
  const summary = data?.summary
  const datePreset = (days: number | 'month' | 'year') => {
    const end = new Date(); const start = new Date()
    if (days === 'month') start.setDate(1)
    else if (days === 'year') { start.setMonth(0, 1) }
    else start.setDate(start.getDate() - days + 1)
    setDraft((current) => ({ ...current, startDate: start.toISOString().slice(0, 10), endDate: end.toISOString().slice(0, 10) }))
  }

  const filtersPanel = <Card className="border-primary/20 bg-gradient-to-r from-primary/10 via-card to-card"><CardContent className="p-4"><div className="flex flex-wrap items-end gap-3"><label className="grid gap-1 text-xs font-medium">From<input type="date" value={draft.startDate} onChange={(e) => setDraft({ ...draft, startDate: e.target.value })} className="h-9 rounded-md border bg-background px-2 text-sm" /></label><label className="grid gap-1 text-xs font-medium">To<input type="date" value={draft.endDate} onChange={(e) => setDraft({ ...draft, endDate: e.target.value })} className="h-9 rounded-md border bg-background px-2 text-sm" /></label><FilterSelect label="City" value={draft.city} values={data?.filters.cities ?? []} onChange={(city) => setDraft({ ...draft, city })}/><FilterSelect label="Source" value={draft.source} values={data?.filters.sources ?? []} onChange={(source) => setDraft({ ...draft, source })}/><FilterSelect label="Category" value={draft.category} values={data?.filters.categories ?? []} onChange={(category) => setDraft({ ...draft, category })}/><label className="grid gap-1 text-xs font-medium">BD<select value={draft.bdId} onChange={(e) => setDraft({ ...draft, bdId: e.target.value })} className="h-9 min-w-36 rounded-md border bg-background px-2 text-sm"><option value="">All BDs</option>{data?.filters.bds.map((bd) => <option key={bd.id} value={bd.id}>{bd.name}</option>)}</select></label><Button onClick={() => setFilters(draft)} disabled={isFetching}>Apply filters</Button><Button variant="outline" onClick={() => { const next = { startDate: firstOfMonth, endDate: today, city: '', source: '', category: '', bdId: '' }; setDraft(next); setFilters(next) }}>Reset</Button></div><div className="mt-3 flex flex-wrap gap-2"><span className="text-xs text-muted-foreground">Quick range:</span>{[['Today', 1], ['Last 7 days', 7], ['Last 30 days', 30], ['Current month', 'month'], ['Current year', 'year']].map(([label, value]) => <button type="button" onClick={() => datePreset(value as number | 'month' | 'year')} className="rounded-full border px-2.5 py-1 text-xs hover:bg-accent" key={label}>{label}</button>)}</div></CardContent></Card>

  return <AuthenticatedLayout><main className="space-y-5 p-4 lg:p-7"><section className="rounded-2xl border border-primary/20 bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 p-6 text-white shadow-xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-300">Business intelligence</p><h1 className="mt-1 text-3xl font-bold">KPI Command Center</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">One permission-scoped view of lead quality, conversion, targets, marketing return and P&L performance.</p></div><div className="rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-right"><p className="text-xs text-slate-300">Selected period</p><p className="font-semibold">{filters.startDate} — {filters.endDate}</p></div></div></section>{filtersPanel}<nav className="flex overflow-x-auto rounded-xl border bg-card p-1">{tabs.map(([key, label, Icon]) => <button key={key} onClick={() => setActive(key)} className={cn('flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium transition', active === key ? 'bg-primary text-primary-foreground shadow' : 'text-muted-foreground hover:bg-muted')}><Icon className="h-4 w-4"/>{label}</button>)}</nav>{isLoading ? <div className="grid min-h-80 place-items-center text-muted-foreground">Loading KPI data…</div> : data && <DashboardSection active={active} data={data} />}</main></AuthenticatedLayout>
}

function FilterSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="grid gap-1 text-xs font-medium">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="h-9 min-w-32 rounded-md border bg-background px-2 text-sm"><option value="">All {label}s</option>{values.map((entry) => <option value={entry} key={entry}>{entry}</option>)}</select></label> }

function DashboardSection({ active, data }: { active: string; data: Data }) {
  const s = data.summary
  if (active === 'salesOverview') return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Total leads" value={s.leads ?? 0} note="Received in selected period"/><MetricCard label="IPD done" value={s.ipd ?? 0} note={`${percent(s.conversionRate)} lead-to-IPD`} tone="sky"/><MetricCard label="Revenue" value={money(s.revenue)} note="P&L records in period" tone="violet"/><MetricCard label="Net profit" value={money(s.netProfit)} note={`${percent(s.netMargin)} net margin`} tone="emerald"/><MetricCard label="Outstanding" value={money(s.outstanding)} note={`${s.outstandingCases} pending cases`} tone="amber"/></div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Lead-to-IPD funnel"><ResponsiveContainer><BarChart data={data.funnel}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label" tick={{ fontSize: 11 }}/><YAxis/><Tooltip/><Bar dataKey="value" fill="#38bdf8" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Monthly lead and IPD trend"><ResponsiveContainer><LineChart data={data.groups.monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis/><Tooltip/><Legend/><RechartsLine type="monotone" dataKey="leads" stroke="#38bdf8" strokeWidth={2}/><RechartsLine type="monotone" dataKey="ipd" stroke="#22c55e" strokeWidth={2}/></LineChart></ResponsiveContainer></ChartCard></div><div className="grid gap-5 xl:grid-cols-2"><GroupTable title="Team performance" rows={data.groups.team}/><GroupTable title="BD performance" rows={data.groups.bd}/></div></div>
  if (active === 'salesTeams') return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Leads" value={s.leads ?? 0}/><MetricCard label="OPD booked" value={s.opdBooked ?? 0} tone="sky"/><MetricCard label="OPD completed" value={s.opdDone ?? 0} tone="violet"/><MetricCard label="Lead to IPD" value={percent(s.conversionRate)} tone="emerald"/></div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Funnel conversion"><ResponsiveContainer><BarChart layout="vertical" data={data.funnel}><XAxis type="number"/><YAxis dataKey="label" type="category" width={100}/><Tooltip/><Bar dataKey="value" fill="#a78bfa" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="City conversion"><ResponsiveContainer><BarChart data={data.groups.city.slice(0,8)}><XAxis dataKey="label"/><YAxis/><Tooltip/><Legend/><Bar dataKey="leads" fill="#38bdf8"/><Bar dataKey="ipd" fill="#22c55e"/></BarChart></ResponsiveContainer></ChartCard></div><div className="grid gap-5 xl:grid-cols-2"><GroupTable title="Source-wise conversion" rows={data.groups.source}/><GroupTable title="City-wise conversion" rows={data.groups.city}/></div></div>
  if (active === 'salesInsights') return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="IPD target" value={data.targets.assigned}/><MetricCard label="Achieved" value={data.targets.achieved} tone="sky"/><MetricCard label="Remaining" value={data.targets.remaining} tone="amber"/><MetricCard label="Achievement" value={percent(data.targets.achievement)} tone="emerald"/><MetricCard label="Projected month end" value={data.targets.projected ?? 'No target'} tone="violet"/></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><ChartCard title="Target versus achieved"><ResponsiveContainer><BarChart data={[{ label: 'IPD', target: data.targets.assigned, achieved: data.targets.achieved, projected: data.targets.projected ?? 0 }]}><XAxis dataKey="label"/><YAxis/><Tooltip/><Legend/><Bar dataKey="target" fill="#64748b"/><Bar dataKey="achieved" fill="#22c55e"/><Bar dataKey="projected" fill="#a78bfa"/></BarChart></ResponsiveContainer></ChartCard><Card><CardHeader><CardTitle className="text-base">Run-rate guidance</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><Line label="Days elapsed" value={data.targets.daysElapsed}/><Line label="Days remaining" value={data.targets.daysRemaining}/><Line label="Current run rate" value={`${data.targets.currentRunRate} IPD/day`}/><Line label="Required run rate" value={`${data.targets.requiredRunRate} IPD/day`}/><p className="rounded-lg bg-muted p-3 text-xs text-muted-foreground">Targets use the active overlap period. Where no IPD or surgery target is assigned, the dashboard shows zero rather than estimating a target.</p></CardContent></Card></div></div>
  if (active === 'marketingAlerts') {
    const campaignsWithoutIpd = data.groups.campaign.filter((row) => row.leads > 0 && row.ipd === 0).length
    const belowAverageSources = data.groups.source.filter((row) => row.leads > 0 && row.conversionRate < (s.conversionRate ?? 0)).length
    return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Campaigns monitored" value={data.groups.campaign.length} tone="sky"/><MetricCard label="No-IPD campaigns" value={campaignsWithoutIpd} tone="rose"/><MetricCard label="Below-average sources" value={belowAverageSources} tone="amber"/><MetricCard label="Overall lead-to-IPD" value={percent(s.conversionRate)} tone="emerald"/><MetricCard label="Cost per IPD" value={money(s.costPerIpd)} tone="violet"/></div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Campaign conversion monitoring"><ResponsiveContainer><BarChart data={data.groups.campaign.slice(0,10)}><XAxis dataKey="label" tick={{fontSize: 10}}/><YAxis/><Tooltip/><Legend/><Bar dataKey="leads" fill="#38bdf8"/><Bar dataKey="ipd" fill="#f43f5e"/></BarChart></ResponsiveContainer></ChartCard><GroupTable title="Source conversion monitoring" rows={data.groups.source}/></div><DataNote>Threshold configuration for high spend, high CPL and low conversion is not yet stored in CRM. This tab therefore shows the live values that will drive those alerts, without applying arbitrary thresholds.</DataNote></div>
  }  if (active === 'marketingOverview' || active === 'marketingPerformance') return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Marketing spend" value={money(s.marketingSpend)} tone="violet"/><MetricCard label="Cost per lead" value={money(s.cpl)} tone="sky"/><MetricCard label="Cost per IPD" value={money(s.costPerIpd)} tone="amber"/><MetricCard label="ROAS" value={s.roas === null ? 'Not available' : `${s.roas}x`} tone="emerald"/><MetricCard label="Marketing ROI" value={s.marketingRoi === null ? 'Not available' : percent(s.marketingRoi)} tone="emerald"/></div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Campaign lead quality"><ResponsiveContainer><BarChart data={data.groups.campaign.slice(0,8)}><XAxis dataKey="label" tick={{fontSize: 10}}/><YAxis/><Tooltip/><Legend/><Bar dataKey="leads" fill="#38bdf8"/><Bar dataKey="ipd" fill="#22c55e"/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Lead source mix"><ResponsiveContainer><PieChart><Pie data={data.groups.source.slice(0,6)} dataKey="leads" nameKey="label" outerRadius={100} label>{colors.map((color, index) => <Cell fill={color} key={index}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></ChartCard></div><GroupTable title="Campaign performance" rows={data.groups.campaign}/></div>
  if (active === 'outstanding') return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Total outstanding" value={money(data.finance.outstanding)} tone="amber"/><MetricCard label="Pending cases" value={data.finance.outstandingCases} tone="rose"/><MetricCard label="P&L records" value={data.finance.plRecords} tone="sky"/><MetricCard label="Due this week" value="Not captured"/><MetricCard label="Overdue aging" value="Not captured"/></div><div className="grid gap-5 xl:grid-cols-2"><GroupTable title="Outstanding source view by hospital" rows={data.groups.hospital}/><GroupTable title="Outstanding source view by category" rows={data.groups.category}/></div><DataNote>Due dates and payment ageing are not stored against each outstanding case yet. The total is accurate from current P&L and outstanding records; age buckets will appear once a due-date field is maintained.</DataNote></div>
  if (active === 'cashFlow') return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Expected collections" value={money(data.finance.outstanding)} tone="amber"/><MetricCard label="Cash / bank balance" value="Not captured"/><MetricCard label="Cash in" value="Not captured"/><MetricCard label="Cash out" value="Not captured"/><MetricCard label="Net cash flow" value="Not captured"/></div><DataNote>Payment installments are available in CRM, but a complete cash-account opening balance and expense ledger are not yet available. This tab deliberately does not estimate cash flow from P&L values.</DataNote></div>
  if (active === 'hospitalPnl') return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Hospital revenue" value={money(data.finance.revenue)} tone="sky"/><MetricCard label="Net profit" value={money(data.finance.netProfit)} tone="emerald"/><MetricCard label="Average profit / IPD" value={money(s.averageProfit)} tone="violet"/><MetricCard label="Net margin" value={percent(s.netMargin)} tone="amber"/></div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Hospital contribution"><ResponsiveContainer><BarChart data={data.groups.hospital.slice(0,10)}><XAxis dataKey="label" tick={{fontSize: 10}}/><YAxis/><Tooltip/><Legend/><Bar dataKey="revenue" fill="#38bdf8"/><Bar dataKey="profit" fill="#22c55e"/></BarChart></ResponsiveContainer></ChartCard><GroupTable title="Hospital P&L" rows={data.groups.hospital}/></div></div>
  if (active === 'profitability') return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Net profit" value={money(data.finance.netProfit)} tone="emerald"/><MetricCard label="Net margin" value={percent(s.netMargin)} tone="sky"/><MetricCard label="Profit / lead" value={money((s.netProfit ?? 0) / Math.max(1, s.leads ?? 0))} tone="violet"/><MetricCard label="Profit / OPD" value={money((s.netProfit ?? 0) / Math.max(1, s.opdDone ?? 0))} tone="amber"/><MetricCard label="Profit / IPD" value={money(s.averageProfit)} tone="emerald"/></div><div className="grid gap-5 xl:grid-cols-2"><GroupTable title="Category profitability" rows={data.groups.category}/><GroupTable title="BD profitability" rows={data.groups.bd}/></div><div className="grid gap-5 xl:grid-cols-2"><GroupTable title="Team profitability" rows={data.groups.team}/><GroupTable title="Circle profitability" rows={data.groups.city}/></div></div>
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="P&L records" value={data.finance.plRecords}/><MetricCard label="Revenue" value={money(data.finance.revenue)} tone="sky"/><MetricCard label="MediEND share" value={money(data.finance.share)} tone="violet"/><MetricCard label="Net profit" value={money(data.finance.netProfit)} tone="emerald"/><MetricCard label="Outstanding" value={money(data.finance.outstanding)} tone="amber"/></div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Revenue and profit by month"><ResponsiveContainer><BarChart data={data.groups.monthly}><XAxis dataKey="label"/><YAxis/><Tooltip/><Legend/><Bar dataKey="revenue" fill="#38bdf8"/><Bar dataKey="profit" fill="#22c55e"/></BarChart></ResponsiveContainer></ChartCard><Card><CardHeader><CardTitle className="text-base">Finance measurement status</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Line label="Average revenue per IPD" value={money(s.averageRevenue)}/><Line label="Average profit per IPD" value={money(s.averageProfit)}/><Line label="Net profit margin" value={percent(s.netMargin)}/><Line label="Pending collection cases" value={data.finance.outstandingCases}/><p className="rounded-lg bg-muted p-3 text-xs text-muted-foreground">Revenue and profit use P&L records. Cash/bank balances, refund ledger and invoice due dates are shown only after those records are maintained in CRM.</p></CardContent></Card></div><div className="grid gap-5 xl:grid-cols-2"><GroupTable title="City profitability" rows={data.groups.city}/><GroupTable title="BD profitability" rows={data.groups.bd}/></div></div>
}
function Line({ label, value }: { label: string; value: string | number }) { return <div className="flex items-center justify-between border-b pb-2"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div> }
function DataNote({ children }: { children: React.ReactNode }) { return <Card className="border-amber-500/30 bg-amber-500/5"><CardContent className="p-4 text-sm text-muted-foreground">{children}</CardContent></Card> }
