-- New platform capabilities for the isolated crm_v2 schema.
-- No object in public is created, changed, or referenced by this script.

BEGIN;

CREATE TABLE crm_v2."StorageProvider" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id text UNIQUE,
  name text NOT NULL,
  provider_type text NOT NULL CHECK (provider_type IN ('LOCAL', 'AWS_S3', 'AZURE_BLOB')),
  is_enabled boolean NOT NULL DEFAULT false,
  is_default boolean NOT NULL DEFAULT false,
  local_root_path text,
  bucket_or_container text,
  region text,
  endpoint text,
  access_key_encrypted text,
  secret_key_encrypted text,
  connection_string_encrypted text,
  created_by_id integer REFERENCES crm_v2."User"(id),
  updated_by_id integer REFERENCES crm_v2."User"(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT storage_provider_configuration_check CHECK (
    (provider_type = 'LOCAL' AND local_root_path IS NOT NULL)
    OR (provider_type = 'AWS_S3' AND bucket_or_container IS NOT NULL AND region IS NOT NULL)
    OR (provider_type = 'AZURE_BLOB' AND bucket_or_container IS NOT NULL)
  )
);
CREATE UNIQUE INDEX "StorageProvider_one_default_idx" ON crm_v2."StorageProvider" (is_default) WHERE is_default;

CREATE TABLE crm_v2."FileAsset" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id text UNIQUE,
  provider_id integer NOT NULL REFERENCES crm_v2."StorageProvider"(id),
  storage_key text NOT NULL,
  original_filename text NOT NULL,
  mime_type text NOT NULL,
  byte_size bigint NOT NULL CHECK (byte_size >= 0),
  checksum_sha256 text,
  entity_type text,
  entity_id integer,
  uploaded_by_id integer REFERENCES crm_v2."User"(id),
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  UNIQUE (provider_id, storage_key)
);
CREATE INDEX "FileAsset_entity_idx" ON crm_v2."FileAsset" (entity_type, entity_id) WHERE NOT is_deleted;

CREATE TABLE crm_v2."Connector" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id text UNIQUE,
  name text NOT NULL,
  connector_type text NOT NULL CHECK (connector_type IN ('GOOGLE', 'FACEBOOK', 'WEBHOOK', 'OTHER')),
  is_enabled boolean NOT NULL DEFAULT false,
  configuration jsonb NOT NULL DEFAULT '{}'::jsonb,
  credentials_encrypted text,
  sync_schedule text,
  last_synced_at timestamptz,
  last_error text,
  created_by_id integer REFERENCES crm_v2."User"(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (connector_type, name)
);

CREATE TABLE crm_v2."ConnectorWebhook" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector_id integer NOT NULL REFERENCES crm_v2."Connector"(id) ON DELETE CASCADE,
  event_name text NOT NULL,
  webhook_path text NOT NULL UNIQUE,
  signing_secret_encrypted text,
  is_enabled boolean NOT NULL DEFAULT true,
  last_received_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (connector_id, event_name)
);

CREATE TABLE crm_v2."DmsFolder" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer REFERENCES crm_v2."DmsFolder"(id) ON DELETE RESTRICT,
  name text NOT NULL,
  path text NOT NULL UNIQUE,
  owner_id integer REFERENCES crm_v2."User"(id),
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE crm_v2."DmsDocument" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folder_id integer REFERENCES crm_v2."DmsFolder"(id) ON DELETE SET NULL,
  document_number text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  document_type text NOT NULL,
  status text NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED')),
  current_version_id integer,
  owner_id integer REFERENCES crm_v2."User"(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz
);

CREATE TABLE crm_v2."DmsDocumentVersion" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id integer NOT NULL REFERENCES crm_v2."DmsDocument"(id) ON DELETE CASCADE,
  file_asset_id integer NOT NULL REFERENCES crm_v2."FileAsset"(id),
  version_number integer NOT NULL CHECK (version_number > 0),
  change_summary text,
  created_by_id integer REFERENCES crm_v2."User"(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (document_id, version_number)
);
ALTER TABLE crm_v2."DmsDocument"
  ADD CONSTRAINT "DmsDocument_current_version_fk"
  FOREIGN KEY (current_version_id) REFERENCES crm_v2."DmsDocumentVersion"(id) ON DELETE SET NULL;

CREATE TABLE crm_v2."DmsAccessGrant" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id integer REFERENCES crm_v2."DmsDocument"(id) ON DELETE CASCADE,
  folder_id integer REFERENCES crm_v2."DmsFolder"(id) ON DELETE CASCADE,
  user_id integer REFERENCES crm_v2."User"(id) ON DELETE CASCADE,
  role_code text,
  permission_level text NOT NULL CHECK (permission_level IN ('VIEW', 'COMMENT', 'EDIT', 'MANAGE')),
  created_by_id integer REFERENCES crm_v2."User"(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dms_access_target_check CHECK ((document_id IS NOT NULL)::integer + (folder_id IS NOT NULL)::integer = 1),
  CONSTRAINT dms_access_subject_check CHECK ((user_id IS NOT NULL)::integer + (role_code IS NOT NULL)::integer = 1)
);

CREATE TABLE crm_v2."DmsWorkflow" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  document_type text,
  is_enabled boolean NOT NULL DEFAULT true,
  created_by_id integer REFERENCES crm_v2."User"(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE crm_v2."DmsWorkflowStep" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workflow_id integer NOT NULL REFERENCES crm_v2."DmsWorkflow"(id) ON DELETE CASCADE,
  step_order integer NOT NULL CHECK (step_order > 0),
  name text NOT NULL,
  approver_role_code text,
  approver_user_id integer REFERENCES crm_v2."User"(id),
  require_all_approvers boolean NOT NULL DEFAULT false,
  UNIQUE (workflow_id, step_order),
  CONSTRAINT dms_workflow_step_approver_check CHECK (approver_role_code IS NOT NULL OR approver_user_id IS NOT NULL)
);

CREATE TABLE crm_v2."DmsWorkflowInstance" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workflow_id integer NOT NULL REFERENCES crm_v2."DmsWorkflow"(id),
  document_id integer NOT NULL REFERENCES crm_v2."DmsDocument"(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'APPROVED', 'REJECTED', 'CANCELLED')),
  current_step_order integer,
  started_by_id integer REFERENCES crm_v2."User"(id),
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE crm_v2."DmsWorkflowTask" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id integer NOT NULL REFERENCES crm_v2."DmsWorkflowInstance"(id) ON DELETE CASCADE,
  step_id integer NOT NULL REFERENCES crm_v2."DmsWorkflowStep"(id),
  assigned_to_id integer REFERENCES crm_v2."User"(id),
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'SKIPPED')),
  comment text,
  acted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE crm_v2."DmsAuditLog" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id integer REFERENCES crm_v2."DmsDocument"(id) ON DELETE CASCADE,
  file_asset_id integer REFERENCES crm_v2."FileAsset"(id) ON DELETE SET NULL,
  actor_id integer REFERENCES crm_v2."User"(id),
  action text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX "DmsDocument_folder_status_idx" ON crm_v2."DmsDocument" (folder_id, status);
CREATE INDEX "DmsDocument_title_search_idx" ON crm_v2."DmsDocument" USING gin (to_tsvector('simple', title || ' ' || coalesce(description, '')));
CREATE INDEX "DmsWorkflowTask_assignee_status_idx" ON crm_v2."DmsWorkflowTask" (assigned_to_id, status);
CREATE INDEX "ConnectorWebhook_connector_idx" ON crm_v2."ConnectorWebhook" (connector_id, is_enabled);

COMMIT;
