-- Converts the isolated crm_v2 copy to integer identities without touching public.
-- It is intentionally transactional: an unmatched relationship aborts all v2 changes.

BEGIN;

CREATE TABLE crm_v2."_V2ForeignKeyMap" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  constraint_name text NOT NULL,
  source_table text NOT NULL,
  source_column text NOT NULL,
  legacy_source_column text NOT NULL,
  target_table text NOT NULL,
  target_column text NOT NULL,
  on_update_action text NOT NULL,
  on_delete_action text NOT NULL,
  source_required boolean NOT NULL
);

INSERT INTO crm_v2."_V2ForeignKeyMap" (
  constraint_name, source_table, source_column, legacy_source_column,
  target_table, target_column, on_update_action, on_delete_action, source_required
)
SELECT
  constraint_row.conname,
  source_table.relname,
  source_column.attname,
  'legacy_' || source_column.attname,
  target_table.relname,
  target_column.attname,
  CASE constraint_row.confupdtype
    WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE'
    WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT'
  END,
  CASE constraint_row.confdeltype
    WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE'
    WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT'
  END,
  source_column.attnotnull
FROM pg_constraint constraint_row
JOIN pg_namespace source_schema ON source_schema.oid = constraint_row.connamespace
JOIN pg_class source_table ON source_table.oid = constraint_row.conrelid
JOIN pg_class target_table ON target_table.oid = constraint_row.confrelid
JOIN unnest(constraint_row.conkey) WITH ORDINALITY source_key(attnum, position) ON true
JOIN unnest(constraint_row.confkey) WITH ORDINALITY target_key(attnum, position)
  ON target_key.position = source_key.position
JOIN pg_attribute source_column ON source_column.attrelid = source_table.oid AND source_column.attnum = source_key.attnum
JOIN pg_attribute target_column ON target_column.attrelid = target_table.oid AND target_column.attnum = target_key.attnum
WHERE source_schema.nspname = 'crm_v2'
  AND constraint_row.contype = 'f'
  AND format_type(source_column.atttypid, source_column.atttypmod) IN ('text', 'character varying');

DO $$
DECLARE item record;
BEGIN
  FOR item IN SELECT constraint_name, source_table FROM crm_v2."_V2ForeignKeyMap" LOOP
    EXECUTE format('ALTER TABLE crm_v2.%I DROP CONSTRAINT %I', item.source_table, item.constraint_name);
  END LOOP;
END $$;

DO $$
DECLARE
  pk record;
  old_column text;
  legacy_columns text[];
  legacy_column text;
BEGIN
  FOR pk IN
    SELECT
      constraint_row.conname AS constraint_name,
      table_row.relname AS table_name,
      array_agg(column_row.attname ORDER BY key_column.position) AS column_names,
      array_agg(format_type(column_row.atttypid, column_row.atttypmod) ORDER BY key_column.position) AS column_types
    FROM pg_constraint constraint_row
    JOIN pg_namespace schema_row ON schema_row.oid = constraint_row.connamespace
    JOIN pg_class table_row ON table_row.oid = constraint_row.conrelid
    JOIN unnest(constraint_row.conkey) WITH ORDINALITY key_column(attnum, position) ON true
    JOIN pg_attribute column_row ON column_row.attrelid = table_row.oid AND column_row.attnum = key_column.attnum
    WHERE schema_row.nspname = 'crm_v2' AND constraint_row.contype = 'p'
    GROUP BY constraint_row.conname, table_row.relname
  LOOP
    -- Tables already using a simple integer id are kept as-is.
    IF cardinality(pk.column_names) = 1
       AND pk.column_names[1] = 'id'
       AND pk.column_types[1] IN ('integer', 'bigint') THEN
      CONTINUE;
    END IF;

    EXECUTE format('ALTER TABLE crm_v2.%I DROP CONSTRAINT %I', pk.table_name, pk.constraint_name);
    legacy_columns := ARRAY[]::text[];

    FOREACH old_column IN ARRAY pk.column_names LOOP
      legacy_column := 'legacy_' || old_column;
      EXECUTE format('ALTER TABLE crm_v2.%I RENAME COLUMN %I TO %I', pk.table_name, old_column, legacy_column);
      EXECUTE format('ALTER TABLE crm_v2.%I ALTER COLUMN %I DROP NOT NULL', pk.table_name, legacy_column);
      legacy_columns := array_append(legacy_columns, legacy_column);
    END LOOP;

    EXECUTE format('ALTER TABLE crm_v2.%I ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY', pk.table_name);
    EXECUTE format('UPDATE crm_v2.%I SET id = DEFAULT WHERE id IS NULL', pk.table_name);
    EXECUTE format('ALTER TABLE crm_v2.%I ALTER COLUMN id SET NOT NULL', pk.table_name);
    EXECUTE format('ALTER TABLE crm_v2.%I ADD CONSTRAINT %I PRIMARY KEY (id)', pk.table_name, 'v2pk_' || left(md5(pk.table_name), 16));
    EXECUTE format(
      'ALTER TABLE crm_v2.%I ADD CONSTRAINT %I UNIQUE (%s)',
      pk.table_name,
      'v2legacy_' || left(md5(pk.table_name), 16),
      (SELECT string_agg(format('%I', column_name), ', ') FROM unnest(legacy_columns) AS column_name)
    );
  END LOOP;
END $$;

DO $$
DECLARE
  relation_row record;
  target_legacy_column text;
  target_has_legacy boolean;
  unmatched_count bigint;
BEGIN
  FOR relation_row IN SELECT * FROM crm_v2."_V2ForeignKeyMap" ORDER BY id LOOP
    SELECT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'crm_v2'
        AND table_name = relation_row.source_table
        AND column_name = relation_row.legacy_source_column
    ) INTO target_has_legacy;

    IF NOT target_has_legacy THEN
      EXECUTE format(
        'ALTER TABLE crm_v2.%I RENAME COLUMN %I TO %I',
        relation_row.source_table, relation_row.source_column, relation_row.legacy_source_column
      );
      EXECUTE format(
        'ALTER TABLE crm_v2.%I ALTER COLUMN %I DROP NOT NULL',
        relation_row.source_table, relation_row.legacy_source_column
      );
    END IF;

    EXECUTE format('ALTER TABLE crm_v2.%I ADD COLUMN %I integer', relation_row.source_table, relation_row.source_column);

    SELECT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'crm_v2'
        AND table_name = relation_row.target_table
        AND column_name = 'legacy_' || relation_row.target_column
    ) INTO target_has_legacy;
    target_legacy_column := CASE
      WHEN target_has_legacy THEN 'legacy_' || relation_row.target_column
      ELSE relation_row.target_column
    END;

    EXECUTE format(
      'UPDATE crm_v2.%1$I AS source_row
       SET %2$I = target_row.id
       FROM crm_v2.%3$I AS target_row
       WHERE source_row.%4$I IS NOT NULL
         AND target_row.%5$I = source_row.%4$I',
      relation_row.source_table,
      relation_row.source_column,
      relation_row.target_table,
      relation_row.legacy_source_column,
      target_legacy_column
    );

    EXECUTE format(
      'SELECT count(*)
       FROM crm_v2.%1$I AS source_row
       LEFT JOIN crm_v2.%2$I AS target_row
         ON target_row.%3$I = source_row.%4$I
       WHERE source_row.%4$I IS NOT NULL AND target_row.id IS NULL',
      relation_row.source_table,
      relation_row.target_table,
      target_legacy_column,
      relation_row.legacy_source_column
    ) INTO unmatched_count;

    IF unmatched_count > 0 THEN
      RAISE EXCEPTION 'Unmatched v2 reference %.% -> %.%: % rows',
        relation_row.source_table, relation_row.source_column,
        relation_row.target_table, relation_row.target_column, unmatched_count;
    END IF;

    IF relation_row.source_required THEN
      EXECUTE format('ALTER TABLE crm_v2.%I ALTER COLUMN %I SET NOT NULL', relation_row.source_table, relation_row.source_column);
    END IF;

    EXECUTE format(
      'ALTER TABLE crm_v2.%I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES crm_v2.%I(id) ON UPDATE %s ON DELETE %s',
      relation_row.source_table,
      'v2fk_' || left(md5(relation_row.source_table || ':' || relation_row.source_column), 20),
      relation_row.source_column,
      relation_row.target_table,
      relation_row.on_update_action,
      relation_row.on_delete_action
    );
  END LOOP;
END $$;

COMMIT;
