export const LEAD_STATUS_OPTIONS = [
  'New',
  'New Lead',
  'Hot Lead',
  'Interested',
  'Follow-up 1',
  'Follow-up 2',
  'Follow-up 3',
  'Follow-up 4',
  'Follow-up 5',
  'Follow-up',
  'Call Back (SD)',
  'Call Back (T)',
  'Call Back Next Week',
  'Call Back Next Month',
  'IPD Schedule',
  'IPD Done',
  'Converted',
  'Closed',
  'Lost',
  'DNP',
  'DNP (1-5, Exhausted)',
  'Junk',
  'Churned',
  'Invalid Number',
  'Fund Issues',
  'Call Done',
  'C/W Done',
] as const
